name: Deploy to EC2 (develop)

on:
  push:
    branches:
      - develop  # developブランチにpushされたとき実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # 1 リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 EC2へSSH接続してデプロイ
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo ">>> Move to project directory"
            cd /home/ec2-user/my-order-app

            echo ">>> Stop current app"
            sudo pm2 stop my-order-app || true

            echo ">>> Pull latest changes"
            git fetch origin develop
            git reset --hard origin/develop

            echo ">>> Install dependencies"
            sudo npm install --production

            echo ">>> Restart app with PM2"
            sudo pm2 start server.js --name my-order-app || sudo pm2 restart my-order-app

            echo ">>> Save PM2 process list"
            sudo pm2 save
